/**
 * The ONLY place in the codebase allowed to import from "lucide-react".
 * To swap icon sets (e.g. to Phosphor, Tabler...), edit only this file.
 */
import {
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  X,
  Check,
  Plus,
  Minus,
  Search,
  Settings,
  Home,
  User,
  Heart,
  Star,
  Info,
  AlertTriangle,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  MoreHorizontal,
  MoreVertical,
  ExternalLink,
  Sun,
  Moon,
  Monitor,
  type LucideIcon,
} from "lucide-react";

import type { IconName } from "./icon.types";

export const iconRegistry: Record<IconName, LucideIcon> = {
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  close: X,
  check: Check,
  plus: Plus,
  minus: Minus,
  search: Search,
  settings: Settings,
  home: Home,
  user: User,
  heart: Heart,
  star: Star,
  info: Info,
  warning: AlertTriangle,
  "alert-circle": AlertCircle,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "more-horizontal": MoreHorizontal,
  "more-vertical": MoreVertical,
  "external-link": ExternalLink,
  sun: Sun,
  moon: Moon,
  monitor: Monitor,
};
