// Single import point for lucide-react (design-tokens-summary.md SS0) --
// no other file in the codebase may import from "lucide-react" directly.
// Swapping icon libraries later only requires editing this file.
import {
  ArrowLeft,
  Bell,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  Clock,
  Copy,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  Heart,
  House,
  Info,
  LoaderCircle,
  Minus,
  Plus,
  Search,
  Settings,
  Share2,
  Sidebar,
  Star,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  X,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const iconRegistry = {
  "arrow-left": ArrowLeft,
  bell: Bell,
  calendar: Calendar,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  circle: Circle,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  clock: Clock,
  close: X,
  copy: Copy,
  download: Download,
  ellipsis: Ellipsis,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  heart: Heart,
  home: House,
  info: Info,
  minus: Minus,
  plus: Plus,
  search: Search,
  settings: Settings,
  share: Share2,
  sidebar: Sidebar,
  spinner: LoaderCircle,
  star: Star,
  trash: Trash2,
  "triangle-alert": TriangleAlert,
  upload: Upload,
  user: User,
} satisfies Record<string, LucideIcon>;
